### PR TITLE
Wishlist v2

### PR DESCRIPTION
**Pull request by anhthang**
This PR to resolve issue #60 

**Done**:

- [x] Migrated to wishlist v2 API
- [x] Update UI

**Preview**:

screencapture-localhost-8000-wishlist-2020-10-21-14_26_34

### CODE REVIEW

**Comment by zekth** [comment]
Looks good. Will dig into. Feel free to join the discord also.

**Review by zekth — CHANGES_REQUESTED** [review]
It is currently possible to have a cap for trade and in wishlist which is odd. Could you correct it?

Also one thing for the Wishlist UI would be cool to have 2 columns aside for big screens for example.

Also we need to add a locastorage migration from `Wishlist` to `Wishlist_V2`

**Comment by zekth** [comment]
Committed the migration step in your branch.

**Comment by anhthang** [comment]
- The cap is only available at tradelist or wishlist
- Updated the Wishlist UI to this

image

**Review by zekth — APPROVED** [review]
Looks good to me. Thanks for porting it!

Polishing of the UI would be nice in the future. Mention @nchristus :)

**Comment by zekth** [comment]
@anhthang it does :)

**Comment by anhthang** [comment]
@zekth That's great, will work on it later 👍

**Pull request merged**
